---
hetzner_api_token: ""
hetzner_server_name: "remote-coding-server"
hetzner_server_type: "cx22"
hetzner_image: "ubuntu-24.04"
hetzner_location: "hel1"
hetzner_ssh_key_name: "remote-coding-key"
hetzner_server_ssh_public_key_path: "~/.ssh/id_rsa.pub"
hetzner_server_ssh_private_key_path: "~/.ssh/id_rsa"

# Volume settings for persistent home directory
hetzner_volume_name: "{{ hetzner_server_name }}-home"
hetzner_volume_size: 10  # GB (minimum 10)
