---
all:
  hosts:
    hetzner_server:
      ansible_host: "{{ hetzner_server_ip }}"
      ansible_user: root
      ansible_ssh_private_key_file: "{{ ssh_private_key_path | default('~/.ssh/id_rsa') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
